name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '10 18 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - name: Fetch
        id: fetch
        uses: yjl9903/fetch-captain@v1
        with:
          ruid: ${{ env.RUID }}
          roomid: ${{ env.ROOM_ID }}
          output: './data/YYYY/MM/DD.csv'

      - name: Push
        continue-on-error: true
        run: |
          git add **/*.csv
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "update: add ${{ steps.fetch.outputs.csv }}"
          git push
